### PR TITLE
Add map links

### PR DESCRIPTION
**Pull request by mplorentz**
This really makes the map header look a lot worse, but it matches the style of the rest of Farese.com 😀 If you have suggestions for improvement, let me know.

### CODE REVIEW

**Comment by dbirks** [comment]
Awesome, I'll check it out.

**Comment by dbirks** [comment]
What wizardry. How did you exactly match the font??

image

**Comment by dbirks** [comment]
Just realized that my computer doesn't have Calibri, so this looks worse than it should. 

image

Looks like Macs don't have Calibri installed by default either, so I'll make a separate issue for that. Other than that, looks good. Merging

**Comment by mplorentz** [comment]
Pro skillz

**Comment by dbirks** [comment]
Has to be

**Pull request merged**
